#!/usr/bin/php
<?php

/**
 * Entry point. You shall not pass!!!
 */

/*
 * Autoload classes
 *
 * @author Luca Pitzoi <luca.pitzoi@sindria.org>
 */
spl_autoload_register(function ($class) {
	if(strpos($class, '\\') !== false){
		$class = str_replace("\\", '/', $class);
	}
    include './' . $class . '.php';
});


Bootstrap::loader();









?>
